version: '3.4'
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.20.0
    ports:
      - 8080:8080
    restart: on-failure:1
    volumes:
      - ./weaviate_data:/var/lib/weaviate # <== set a volume here
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 8040:8040
    volumes:
      - ./backend:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8040
    depends_on:
      - weaviate

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 8030:8080
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    depends_on:
      - backend
    
